config/routes.rb
Rails.application.routes.draw do
  root to: 'check_lists#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :check_lists, param: :token, format: true, defaults: { format: :html }, only: [:create, :show] do
    resources :items, only: [:create, :update, :show]

    member do
      get 'app'
      get 'manifest'
      get 'service_worker'
      post 'cleanup', to: 'check_lists#cleanup'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_list.rb
# == Schema Information
#
# Table name: check_lists
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  token      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CheckList < ApplicationRecord
  has_many :items
  
  validates :title, presence: true
  validates :token, presence: true, uniqueness: true
  
  # will be used for generating the urls in rails path helpers
  def to_param
    token
  end
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id            :integer          not null, primary key
#  name          :string           not null
#  checked       :boolean          not null
#  check_list_id :integer          not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Item < ApplicationRecord
  belongs_to :check_list

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? || request.format.js? }
end

app/controllers/check_lists_controller.rb
class CheckListsController < ApplicationController
  before_action :set_check_list, only: [:cleanup, :show, :manifest, :app, :service_worker]

  def new
    @check_list = CheckList.new
  end

  def create
    @check_list = CheckList.new(check_list_params)
    @check_list.token = Array.new(16) { [*'a'..'z', *'A'..'Z', *'0'..'9'].sample }.join 

    if @check_list.save
      redirect_to @check_list
    else
      render 'new'
    end
  end

  def show
    @items = @check_list.items.order(created_at: :desc).to_a   # call to_a, because we want the dummy item not be part of the collection
    @item = @check_list.items.new
  end

  def cleanup
    @check_list.items.where(checked: true).destroy_all

    redirect_to @check_list
  end

  private

  def check_list_params
    params.require(:check_list).permit(:title)
  end

  def set_check_list
    @check_list = CheckList.find_by_token(params[:token])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @check_list = CheckList.find_by_token(params[:check_list_token])
    @item = @check_list.items.new(item_params)
    @item.checked = false

    if @item.save
      redirect_to @check_list
    else
      render html: 'Fehler'
    end
  end

  def update
    @check_list = CheckList.find_by_token(params[:check_list_token])
    @item = @check_list.items.find(params[:id])

    if @item.update(item_params)
      head :ok
    else
      render html: 'Fehler'
    end
  end
  
  private

  def item_params
    params.require(:item).permit(:name, :checked)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_lists_helper.rb
module CheckListsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/check_lists/app.js.erb
// Copyright 2016 Google Inc.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


(function() {
  'use strict';

  // TODO add service worker code here
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker
             .register('<%= service_worker_check_list_path(@check_list, :js) %>')
             .then(function() { console.log('Service Worker Registered'); });
  }
})();

app/views/check_lists/manifest.json.erb
{
  "name": "<%= @check_list.title %>",
  "short_name": "<%= @check_list.title %>",
  "icons": [{
    "src": "<%= asset_path 'icon-128x128.png' %>",
      "sizes": "128x128",
      "type": "image/png"
    }, {
      "src": "<%= asset_path 'icon-144x144.png' %>",
      "sizes": "144x144",
      "type": "image/png"
    }, {
      "src": "<%= asset_path 'icon-152x152.png' %>",
      "sizes": "152x152",
      "type": "image/png"
    }, {
      "src": "<%= asset_path 'icon-192x192.png' %>",
      "sizes": "192x192",
      "type": "image/png"
    }, {
      "src": "<%= asset_path 'icon-256x256.png' %>",
      "sizes": "256x256",
      "type": "image/png"
    }],
  "start_url": "<%= check_list_path(@check_list) %>",
  "display": "standalone",
  "background_color": "#3E4EB8",
  "theme_color": "#2F3BA2"
}

app/views/check_lists/new.html.erb
<%= form_for @check_list do |f| %>
 
  <%= f.text_field :title, autofocus: true, required: true %>

  <%= f.submit %>
<% end %>

app/views/check_lists/service_worker.js.erb
// Copyright 2016 Google Inc.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

var dataCacheName = '<%= "data-cache-item-list-#{@check_list.token}" %>';
var cacheName = '<%= "cache-item-list-#{@check_list.token}" %>';
var filesToCache = [
  '/',
  '<%= check_list_path(@check_list) %>',
  '<%= service_worker_check_list_path(@check_list, :js) %>',
  '<%= app_check_list_path(@check_list, :js) %>'
];

self.addEventListener('install', function(e) {
  console.log('[ServiceWorker] Install');
  e.waitUntil(
    caches.open(cacheName).then(function(cache) {
      console.log('[ServiceWorker] Caching app shell');
      return cache.addAll(filesToCache);
    })
  );
});

self.addEventListener('activate', function(e) {
  console.log('[ServiceWorker] Activate');
  e.waitUntil(
    caches.keys().then(function(keyList) {
      return Promise.all(keyList.map(function(key) {
        if (key !== cacheName && key !== dataCacheName) {
          console.log('[ServiceWorker] Removing old cache', key);
          return caches.delete(key);
        }
      }));
    })
  );
  /*
   * Fixes a corner case in which the app wasn't returning the latest data.
   * You can reproduce the corner case by commenting out the line below and
   * then doing the following steps: 1) load app for first time so that the
   * initial New York City data is shown 2) press the refresh button on the
   * app 3) go offline 4) reload the app. You expect to see the newer NYC
   * data, but you actually see the initial data. This happens because the
   * service worker is not yet activated. The code below essentially lets
   * you activate the service worker faster.
   */
  return self.clients.claim();
});

self.addEventListener('fetch', function(e) {
  console.log('[Service Worker] Fetch', e.request.url);
  var dataUrl = 'https://query.yahooapis.com/v1/public/yql';
  if (e.request.url.indexOf(dataUrl) > -1) {
    /*
     * When the request URL contains dataUrl, the app is asking for fresh
     * weather data. In this case, the service worker always goes to the
     * network and then caches the response. This is called the "Cache then
     * network" strategy:
     * https://jakearchibald.com/2014/offline-cookbook/#cache-then-network
     */
    e.respondWith(
      caches.open(dataCacheName).then(function(cache) {
        return fetch(e.request).then(function(response){
          cache.put(e.request.url, response.clone());
          return response;
        });
      })
    );
  } else {
    /*
     * The app is asking for app shell files. In this scenario the app uses the
     * "Cache, falling back to the network" offline strategy:
     * https://jakearchibald.com/2014/offline-cookbook/#cache-falling-back-to-network
     */
    e.respondWith(
      caches.match(e.request).then(function(response) {
        return response || fetch(e.request);
      })
    );
  }
});

app/views/check_lists/show.html.erb
<% content_for :title do %>
  <%= @check_list.title %>
<% end %>

<% content_for :head do %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="canonical" href="https://weather-pwa-sample.firebaseapp.com/final/">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="manifest" href="<%= manifest_check_list_path(@check_list, :json) %>">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="<%= @check_list.title %>">
  <link rel="apple-touch-icon" href="<%= asset_path 'icon-152x152.png' %>">
  <meta name="msapplication-TileImage" content="<%= asset_path 'icon-144x144.png' %>">
  <meta name="msapplication-TileColor" content="#2F3BA2">
  <%= stylesheet_link_tag 'bootstrap.min', media: 'all' %>
<% end %>

<nav class="navbar navbar-dark bg-secondary">
  <span class="navbar-brand mb-0 h1">
    <%= @check_list.title %>
  </span>

  <%= link_to cleanup_check_list_path, method: :post, data: { confirm: 'Delete checked items?' }, class: 'btn btn-warning btn-circle' do %>
    <%= image_tag 'erase.png', height: 20 %>
  <% end %>
</nav>

<div class="list-group">
  <div class="list-group-item">
    <%= form_for [ @check_list, @item ], html: { class: 'form-inline' } do |f| %>

      <div class="form-group mr-2 mb-0">
        <%= f.text_field :name, required: true, autocomplete: 'off', class: 'form-control', style: 'padding-left: 30px;' %>
        
      </div>
      <%= image_tag 'mic.png', id: 'item_name_mic', height: 20, onclick: 'record();', style: 'position: absolute; cursor: pointer; left: 25px;' %>
    
      <%= f.submit '+', class: 'btn btn-primary mb-0' %>
    
    <% end %>
  </div>

  <% @items.each do |item| %>
    <%= link_to check_list_item_path(@check_list, item, item: { checked: !item.checked }), method: :patch, remote: true, class: 'list-group-item list-group-item-action' do %>
      <% if item.checked %>
        <big style="color: darkgray"><strike><%= item.name %></strike></big>
      <% else %>
        <big><%= item.name %></big>
      <% end %>
    <% end %>
  <% end %>
</div>

<script src="<%= app_check_list_path(@check_list, :js) %>" async></script>

<script>
function record() {
  // request permissions to use microphone
  //navigator.mediaDevices.getUserMedia({ audio: true });

  var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition
  var recognition = new SpeechRecognition();
  recognition.lang = 'de-DE';
  recognition.onresult = function(event) { 
    document.getElementById('item_name').value = event.results[0][0].transcript;
  }

  recognition.onstart = function(event) {
    document.getElementById("item_name_mic").style.webkitFilter = "blur(5px)";
  }

  recognition.onend = function(event) {
    document.getElementById("item_name_mic").style.webkitFilter = "";
  }

  recognition.start();
}
   
</script>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if content_for?(:title) %>
        <%= yield(:title) %>
      <% else %>
        CheckList
      <% end %>
    </title>

    <%= yield(:head) %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>